# Project information
site_name: Python Refresher
site_url: https://arcelopera.github.io/PythonRefresher
site_description: Python and coding refresher.
site_author: ArceLopera

# Repository
repo_url: https://github.com/ArceLopera/PythonRefresher
repo_name: ArceLopera/PythonRefresher
edit_uri: "" #disables edit button

# Copyright
copyright: Copyright &copy; 2022

# Social media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ArceLopera
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/carlos-arcelopera
    - icon: fontawesome/brands/github
      link: https://github.com/ArceLopera
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/
    - icon: fontawesome/solid/paper-plane
      link: mailto:arcelopera.carlos@gmail.com

# Configuration
theme:
  name: material
  logo: Images/logo.png
  favicon: Images/favicon.ico
  palette:
    
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition # alerts
  - pymdownx.details #  collapsible alerts
  - pymdownx.superfences # nest code and content inside alerts
  - attr_list # add HTML and CSS to Markdown elements
  - pymdownx.inlinehilite # inline code highlights
  - pymdownx.keys # show keystroke symbols
  - pymdownx.snippets # insert content from other files
  - footnotes
  - def_list
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      toc_depth: 4

# Plugins
plugins:
  - search


# Extra JS
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Python Basics: 
     - General: pythonRefresh.md
     - Variables and Assignments: 
        - Variables: PR/pyVar1.md
        - Type Casting: PR/pyVar2.md
        - Scope of Variables: PR/pyVar3.md
        - del Keyword: PR/pyVar4.md
     - Strings:
        - Backslashes: PR/pyStr1.md
        - String operations: PR/pyStr2.md
        - String functions: PR/pyStr5.md
        - String formatting: PR/pyStr3.md
        - String formatting specifications: PR/pyStr4.md
     - Operators:
        - Arithmethic: PR/pyOp1.md
        - Bitwise: PR/pyOp2.md
        - In-Place: PR/pyOp3.md
        - Walrus: PR/pyOp4.md
        - Comparison: PR/pyOp5.md
        - /@: PR/pyOp6.md
        - (star) *: PR/pyOp7.md
     - Exceptions: PR/pyExp.md
     - Assertions: PR/pyAsser.md
     - Control Flow:
        - For-loops: PR/pyfor.md
        - While-loops: PR/pyWhile.md
        - Else-4loopsExcep: PR/pyElse.md
        - Conditionals: PR/pyCond.md
        - Comprehensions: PR/pyCompr.md
  - Data Structures:
     - General : DS/pyDS.md 
     - Collections:
        - Lists : DS/pyList.md
        - Iterable Functions :
          - Sorted: DS/pyIterSorted.md
          - Map & Filter: DS/pyIterMapFilter.md
          - All & Any: DS/pyIterAllAny.md
          - Enumerate: DS/pyIterEnumerate.md
          - Zip: DS/pyIterZip.md
          - Reversed: DS/pyIterReversed.md
        - Tuple : DS/pyTuple.md
        - Dictionary : DS/pyDict.md
        - Array: DS/pyArray.md
     - Generators : DS/pyGen.md
     - Generator Expressions : DS/pyGenX.md

